/*
 * dlgConfirm.java
 *
 */
package uth.cine.view.swing.principal;

import cineapp.CineApp;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import uth.cine.domain.entities.Employee;
import uth.cine.domain.services.ServiceFactory;
import uth.cine.view.images.ImageLoader;
import uth.cine.view.swing.ErrorDialog;

/**
 *
 * @author  DEVELOP
 */
public class dlgConfirmUser extends javax.swing.JDialog {

    /** A return status code - returned if Cancel button has been pressed */
    public static final int RET_CANCEL = 0;
    /** A return status code - returned if OK button has been pressed */
    public static final int RET_OK = 1;

    public dlgConfirmUser(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setIconImage(ImageLoader.LogoIcon.getImage());
        this.lblLogo.setIcon(ImageLoader.LogoIcon);
        this.setFecha();
        this.tiendaLbl.setText("Bienvenidos");
        
    }

    /** @return the return status of this dialog - one of RET_OK or RET_CANCEL */
    public int getReturnStatus() {
        return returnStatus;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnCancelar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtUsuario = new javax.swing.JTextField();
        txt = new javax.swing.JLabel();
        txt1 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        lblLogo = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        tiendaLbl = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Confirmación");
        setIconImage(null);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, -1, 30));

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, -1, 30));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUsuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyPressed(evt);
            }
        });
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 180, -1));

        txt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt.setText("Usuario:");
        jPanel1.add(txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, 20));

        txt1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt1.setText("Contraseña:");
        jPanel1.add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, -1, -1));

        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPasswordKeyPressed(evt);
            }
        });
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 180, -1));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uth/cine/view/images/puntoventa24.png"))); // NOI18N
        lblLogo.setFocusable(false);
        jPanel1.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 430, 80));

        lblFecha.setFont(new java.awt.Font("Arial", 1, 8)); // NOI18N
        lblFecha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFecha.setText("/ /");
        lblFecha.setFocusable(false);
        jPanel1.add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 120, 40));

        tiendaLbl.setBackground(new java.awt.Color(255, 255, 255));
        tiendaLbl.setFont(new java.awt.Font("Edwardian Script ITC", 1, 32)); // NOI18N
        tiendaLbl.setText("La Comercial");
        tiendaLbl.setFocusable(false);
        jPanel1.add(tiendaLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 10, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 200));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        doClose(RET_CANCEL);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        this.validar();
    }//GEN-LAST:event_btnAceptarActionPerformed
    private void validar() {
        try {
            if (this.valido()) {
                doClose(RET_OK);
            } else {
                /*no hace nada*/
                JOptionPane.showMessageDialog(null, "Usuario y/o Contraseña no valido!!,\n intenta de nuevo");
                this.txtPassword.setText("");
                this.requestFocus();
            }
        } catch (Exception ex) {
            Logger.getLogger(dlgConfirmUser.class.getName()).log(Level.SEVERE, null, ex);
            ErrorDialog.showDialog(ex, "Warning", "No se puede validar el usuario. ");
        }
    }
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        doClose(RET_CANCEL);
    }//GEN-LAST:event_formWindowClosing

private void txtUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyPressed
    this.managerEnterCancel(evt);
}//GEN-LAST:event_txtUsuarioKeyPressed

    @SuppressWarnings("static-access")
private void txtPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyPressed
        if ((evt.getKeyCode() == 10) && (!this.txtUsuario.getText().equals("") && (!this.txtPassword.getPassword().equals("")))) {
            this.validar();
        /*this.btnAceptar.requestFocus();*/
        } else if ((evt.getKeyCode() == evt.VK_ESCAPE)) {
            doClose(RET_CANCEL);
        }
}//GEN-LAST:event_txtPasswordKeyPressed
   
    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    private void setFecha() {
        this.lblFecha.setText(CineApp.fechaActual());
    }

    private boolean valido() throws Exception {
        boolean valido = false;
        char passArray[] = this.txtPassword.getPassword();

        for (int i = 0; i < passArray.length; i++) {
            char c = passArray[i];
            // Si no es letra o numero entonces no es valido
            if (!Character.isLetterOrDigit(c)) {
                JOptionPane.showMessageDialog(null, "No se aceptan caracteres especiales");
                valido = false;
            } /*end letras o digitos*/ else {
            }/*end else*/
        }
        try {
        Employee em =  ServiceFactory.getEmployeeService().getUser(this.txtUsuario.getText(), new String(passArray));
        if (em!=null){
          valido = true;
        }
        } catch (Exception ex) {}
        return valido;
    }

    @SuppressWarnings("static-access")
    private void managerEnterCancel(java.awt.event.KeyEvent evt) {

        //System.out.println(evt.getKeyCode() + " y " + evt.VK_ESCAPE );
        if ((evt.getKeyCode() == 10) && (!this.txtUsuario.getText().equals("") && (!this.txtPassword.getPassword().equals("")))) {
            this.txtPassword.requestFocus();
        } else if ((evt.getKeyCode() == evt.VK_ESCAPE)) {
            doClose(RET_CANCEL);
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAceptar;
    public javax.swing.JButton btnCancelar;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextArea jTextArea1;
    public javax.swing.JLabel lblFecha;
    public javax.swing.JLabel lblLogo;
    public javax.swing.JLabel tiendaLbl;
    public javax.swing.JLabel txt;
    public javax.swing.JLabel txt1;
    public javax.swing.JPasswordField txtPassword;
    public javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
    private int returnStatus = RET_CANCEL;
}
